# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Fajardo Valenti's Blog
email: dfv78@msn.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Blog! I'm an Azure Cloud Solutions Architect and the purpose of this blog is to share information about Cloud Computing and Microsoft Azure.
  

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daniel-fv.github.io" # the base hostname & protocol for your site
twitter_username: dfv78
github_username:  daniel-fv

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
include: ['_pages']

kramdown:
  input: GFM

# Theme
theme: jekyll-theme-architect
